create table if not exists public.members (
  id bigint generated by default as identity primary key,
  username text not null unique,
  created_at timestamptz not null default now()
);

alter table public.members
  add column if not exists password text not null default '',
  add column if not exists nickname text not null default '',
  add column if not exists bank_name text not null default '',
  add column if not exists account_number text not null default '',
  add column if not exists exchange_password text not null default '',
  add column if not exists phone_number text not null default '',
  add column if not exists referral_code text not null default '',
  add column if not exists signup_code text not null default '',
  add column if not exists site_name text not null default '';

alter table public.members
  alter column password drop default,
  alter column nickname drop default,
  alter column bank_name drop default,
  alter column account_number drop default,
  alter column exchange_password drop default,
  alter column phone_number drop default,
  alter column referral_code drop default,
  alter column signup_code drop default,
  alter column site_name drop default;

alter table public.members enable row level security;

drop policy if exists "Allow all inserts on members" on public.members;
drop policy if exists "Allow all selects on members" on public.members;

create policy "Allow all inserts on members"
on public.members
for insert
to anon, authenticated
with check (true);

create policy "Allow all selects on members"
on public.members
for select
to anon, authenticated
using (true);
